library(ggplot2)
library(Rmisc)
library(ggpubr)
source("C:/Users/Mr.wang/Desktop/bishe/source/splitviolinplots.R",local = TRUE)
data <- read.csv("C:/Users/Mr.wang/Desktop/bishe/data1.csv",header = T)
Group <- as.factor(data[,2])
Attribute <- as.factor(data[,3])
data1 <- data.frame(value=data[,1],Group=Group,Attribute=Attribute)
Data_summary <- summarySE(data1, measurevar="value", groupvars=c("Group","Attribute"))
